name: Build and Deploy to Prod

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: resultsquare/rs-server-api
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Deploy Docker Container to Admin EC2 instance
        env:
            PRIVATE_KEY: ${{ secrets.AWS_ADMIN_DASHBOARD_PRIVATE_KEY }}
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_EC2_HOST_NAME }}@${{ secrets.AWS_ADMIN_DASHBOARD_INSTANCE_IP }} "bash ./deploy.sh"
